# Generated by Django 6.1 on 2026-09-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
