# Generated by Django 6.1 on 2026-09-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_deadline_event_details_event_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
