# Generated by Django 6.1 on 2026-09-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_member_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
