# Generated by Django 6.1 on 2026-09-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_member_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='description',
        ),
    ]
