# Generated by Django 6.1 on 2026-09-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_recruitmentsettings_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='competences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='github_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='type_candidature',
            field=models.CharField(default='adherent', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
