# Generated by Django 6.1 on 2026-09-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='fichier_url',
        ),
        migrations.AddField(
            model_name='resource',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
